#!/usr/bin/env node
import { readFile } from 'node:fs/promises';
const port=Number(process.env.CODEX_DEBUG_PORT||9229); const payload=await readFile(new URL('../theme/theme-inject.js',import.meta.url),'utf8'); const deadline=Date.now()+Number(process.env.CODEX_DEBUG_WAIT_MS||12000);
const listTargets=async()=>{const l=await fetch(`http://127.0.0.1:${port}/json/list`).then(r=>r.json());return l.filter(t=>t.type==='page'&&t.webSocketDebuggerUrl&&!String(t.url).startsWith('devtools://')&&String(t.url).startsWith('app://-/'))};
let targets=[]; while(!targets.length&&Date.now()<deadline){try{targets=await listTargets();}catch{} if(!targets.length)await new Promise(r=>setTimeout(r,250));}
if(!targets.length)throw new Error(`No Codex renderer target on 127.0.0.1:${port}`);
async function apply(target){const ws=new WebSocket(target.webSocketDebuggerUrl);let id=0;const call=(m,p)=>new Promise((res,rej)=>{const n=++id;const h=e=>{const x=JSON.parse(e.data);if(x.id===n){ws.removeEventListener('message',h);res(x)}};ws.addEventListener('message',h);ws.send(JSON.stringify({id:n,method:m,params:p}));setTimeout(()=>rej(Error(`Timed out: ${m}`)),5000)});try{await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true})});const domDeadline=Date.now()+Number(process.env.CODEX_DOM_WAIT_MS||10000);let ready=false;while(!ready&&Date.now()<domDeadline){const p=await call('Runtime.evaluate',{expression:'Boolean(document.documentElement && document.head)',returnByValue:true});ready=p.result?.result?.value===true;if(!ready)await new Promise(r=>setTimeout(r,200));}if(!ready)throw Error('DOM not ready');const r=await call('Runtime.evaluate',{expression:payload,returnByValue:true,awaitPromise:true});const v=r.result?.result?.value;return {targetId:target.id,url:target.url,result:v||{ok:false}}}finally{ws.close();}}
const results=[];for(const t of targets){try{results.push(await apply(t));}catch(e){results.push({targetId:t.id,url:t.url,error:e.message});}}
const applied=results.filter(x=>x.result?.ok);if(!applied.length)throw new Error(`No renderer accepted theme: ${JSON.stringify(results)}`);console.log(JSON.stringify({ok:true,targets:results}));
